version: '2'
services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
